### ISSUE TITLE
External indexing settings

### ISSUE THREAD

**Issue by PeterIvanov** [atteo/classindex#17]
Currently, it is only possible to index classes based on their annotated superclass or meta-annotated annotation. To do so, those "markers" must not belong to foreign lib or java classlib - and due to this limitation it is impossible to find, say, all Serializable classes in your project with ClassIndex. 
Some way of external configuration is required to fix this.

**Comment by sentinelt** [comment]
I don't plan to implement this. I am not even sure if external configuration is even possible. I will gladly accept pull request, though.
