### ISSUE TITLE
Question: Will ClassIndex scan subpackages when using package-info.java?

### ISSUE THREAD

**Issue by christianbalzer** [atteo/classindex#23]
Will ClassIndex scan subpackages when using package-info.java?

That bit of information is missing from the home page, I think. Maybe I just missed it, though... :-)
https://github.com/atteo/classindex#class-indexing

Also, it looks like the level two list's markup didn't really work out in that paragraph...

**Comment by sentinelt** [comment]
The answer is no. I updated README page to make that clear. I've also updated unit test to make that sure.

**Comment by christianbalzer** [comment]
Sorry, I haven't quite figured out how to contact devs on github, other than through bug reports...
Is there an easy way to make it do that? :)

**Comment by sentinelt** [comment]
Actually there is, every commit in Git contains the email address :-)
I don't mind opening the ticket for such omissions though.

**Comment by sentinelt** [comment]
On the second reading.. if you are asking if recursive scanning through packages is doable... yes, I think so.
