### ISSUE TITLE
Indexing Annotation- Custom Processor

### ISSUE THREAD

**Issue by nandhusriram** [atteo/classindex#26]
I have the custom processor included   as a jar dependency and when I trying to index based on certain annotation ,zero classes gets indexed, does the custom processor needs to be same project as the other one.

**Comment by sentinelt** [comment]
There are several things which might be broken in your case. Notice that:

1. The custom processor needs to be available on the classpath during compilation.
2. The above rule also implies that the custom processor cannot be in the same project as the indexed classes (well it can, but then maven-compiler-plugin configuration needs to be changes as was done here: https://github.com/atteo/classindex/blob/master/classindex/pom.xml)
3. The custom processor "sees" only classes which are compiled. So for instance it won't index classes from 3rd party jars.
