### ISSUE TITLE
Processor Error when compiling a NetBeans platform project

### ISSUE THREAD

**Issue by SirIntellegence** [atteo/classindex#27]
Here is the link to the example project:
https://app.box.com/s/rh5nvgd5bmcotbgfafy5b3apmr7g1hd4
It fails to build in netbeans with the message:
error: [ClassIndexProcessor] Can't write index file: Attempt to reopen a file for path Code Test\BugKiller3\Module1\target\classes\com\example\bugkiller3\module1\jaxb.index
Edit:
Note: I just noticed some identifiable info in that.... Just a moment while I fix that...
Edit2:
Fixed

**Comment by sentinelt** [comment]
Thanks for the report and especially for the example project. With it the problem was easy to identify.
