### ISSUE TITLE
Adding custom ClassIndexProcessor breaks Maven build

### ISSUE THREAD

**Issue by jdhoek** [atteo/classindex#31]
In a Maven project, ClassIndex works when I annotate the scanned annotations with `@IndexAnnotated`. But when I try implementing a custom `ClassIndexProcessor`, the compiled java classes seem to be missing from the build as soon as I build the project with my custom processor listed in `META-INF/services/javax.annotation.processing.Processor`.

I have created a bare bones minimal working example of the problem I am seeing:

https://github.com/LableOrg/classindex-compilation-issue

In this example, if I comment out my class in `META-INF/services/javax.annotation.processing.Processor`, the project builds, and can be run:

```
mvn clean install
mvn exec:java
```

Of course, no classes are found by ClassIndex, because the annotation it is looking for is not annotated with `@IndexAnnotated`.

Now if I run this example project as-is, leaving my custom class in the services file, the compiled Java classes end up missing in the `target` directory.

Is this a bug in ClassIndex, or am I using it wrong? Can you reproduce this issue with my example?

**Comment by sentinelt** [comment]
Hi, thanks for the report. I will try to reproduce this problem during the weekend.

**Comment by sentinelt** [comment]
Sorry for late response. There is a chicken and egg problem here. File 'META-INF/services/javax.annotation.processing.Processor' is already read when you CustomProcessor.java. At that time your CustomProcessor is not yet compiled so it is not available.

Another problem is that the javac error reporting is sometimes not working correctly in older Java versions. With openjdk version 1.8.0_45 I got:

  Provider org.example.classindexprocessorttest.CustomProcessor not found

You need to have CustomProcessor in a separate Maven project or use special compiler execution in the POM file to compile it with annotation processing disabled. An example of such configuration can be found here: https://github.com/atteo/classindex/blob/master/classindex/pom.xml#L42
