### ISSUE TITLE
Android with Gradle

### ISSUE THREAD

**Issue by albertvaka** [atteo/classindex#32]
Hi there! Should this just work if I add it to my Android build.gradle? I didn't manage to make it work: getSubclasses doesn't return anything (and yup, I have the right annotation in the parent class). Should it just work on Android, or am I missing something?

**Comment by albertvaka** [comment]
Any update on this?

**Comment by tinsukE** [comment]
ClassIndex creates (very slim) class list files at compile time that is then loaded at runtime by the Java app so no runtime Annotation scanning is needed.

Your problem is that the generated files are not bundled in the APK. To fix that, add this to the bottom of your **build.gradle** file (the same one where you declare `compile org.atteo.classindex:classindex:...`):

```gradle
// Package the preprocessed Annotations (ClassIndex) into the APK
tasks.withType(PackageApplication) { pkgTask ->
    android.applicationVariants.all { variant ->
        def String variantName = variant.getName().capitalize()
        if (pkgTask.getName().indexOf(variantName) != -1) {
            pkgTask.setJavaResourceDir(new File(buildDir, "intermediates/classes/$variant.dirName"))
        }
    }
}
```

Also note that the version 3.3 of the library uses the `java.nio.charset.StandardCharsets` class, which was only introduced in Android API 19 (KitKat), so if you want to support any API lower than that you're gonna have to work that around by either:
1. Adding the StandardCharsets.java to your project (which should trigger a HUGE error on gradle, but I can provide a fix for that); or
2. Adding a copy of ClassIndex.java to your project (the master branch already has this fix).

Let me know if you find any issues with it!

**Comment by albertvaka** [comment]
@tinsukE Thanks a lot for your help! I had to modify your snippet a little bit (it was complaining about PackageApplication not defined) but now it seems to work just fine. This is my final code in case it's useful to somebody:
```
project.android.applicationVariants.all { variant ->
    variant.outputs.each { output ->
        def pkgTask = output.packageApplication
        def String variantName = variant.getName().capitalize()
        if (pkgTask.getName().indexOf(variantName) != -1) {
            pkgTask.setJavaResourceDir(new File(buildDir, "intermediates/classes/$variant.dirName"))
        }
    }
}
```

It's a pity that the last released version (3.3) doesn't include the fix for Android < 19. @sentinelt Any plans for a new release?

**Comment by albertvaka** [comment]
@sentinelt Can we have an answer? Even a "No, i'm busy with other stuff and can't make a new maven release" is good enough, if that's the case, so I can plan accordingly. Thanks a lot!

**Comment by sentinelt** [comment]
Sorry for the delay. I just released 3.4.

**Comment by albertvaka** [comment]
Thanks a lot for your time Sławek, your work is greatly appreciated :)

@tinsukE: I think you can now also use the new release instead of your workaround.

**Comment by omerduzyol** [comment]
@albertvaka @tinsukE 

Hi guys,

I'm trying to use your solution with newest version of gradle but setJavaResourceDir(..) method is missing and I couldn't find a replacement... Do you have any idea to put generated cache files into APK?

Thanks in advance!

**Comment by omerduzyol** [comment]
I solved by copying files from classes to JavaResources folder.

```
// Package the preprocessed Annotations (ClassIndex) into the APK
tasks.withType(com.android.build.gradle.tasks.PackageApplication) { pkgTask ->
    android.applicationVariants.all { variant ->
        def String variantName = variant.getName().capitalize()
        if (pkgTask.getName().indexOf(variantName) != -1) {
            copy {
                from new File(buildDir, "intermediates/classes/$variant.dirName/META-INF/annotations/")
                into new File(buildDir, "intermediates/sourceFolderJavaResources/$variant.dirName/META-INF/annotations/");
            }
        }
    }
}
```

**Comment by trolloks** [comment]
Does this also apply, when the parent class is situated in an apklib? I have subclasses declared in my library and subclasses defined in my application. getSubClasses() is currently only returning the subclasses in the library and not the application? Sorry if I'm posting this in the incorrect thread.

**Comment by dima74** [comment]
This works for me:
```
android {
	sourceSets {
		main.resources.srcDirs = ["build/intermediates/classes/debug"]
	}
}
```
(Add this to build.gradle file of your module)

**Comment by dima74** [comment]
@omerduzyol Thank you for your code!
My version (previous post) doesn't work with Instant Run, and your works! I just replace `...META-INF/annotations...` for `...META-INF/services...`
