### ISSUE TITLE
The ClassIndexing and runnable jar

### ISSUE THREAD

**Issue by costaplih** [atteo/classindex#33]
hi ,
I have an issue with your framework, i use 3.3 version, all is working fine from eclipse but when exporting to runnable jar its not working any more (the jar is runnable and working only the mechanism is not) could you please assist on this ?

**Comment by costaplih** [comment]
Any updates ?

**Comment by sentinelt** [comment]
Sorry for late response. Classindex creates indexes during compilation which are later retrieved at run-time. One thing which might be broken is that the index files are not in the runnable jar. Another issue might be that they are overwritten, see https://github.com/atteo/classindex#making-shaded-jar.
