### ISSUE TITLE
ProGuard

### ISSUE THREAD

**Issue by milankos19** [atteo/classindex#37]
After I enabled  ProGuard,  method  ClassIndex.getAnnotated(myAnnotaion.class) didn't find  any class ? I use classindex in android library project.

**Comment by sentinelt** [comment]
hi, correct me if I am wrong, but from what I read ProGuard obfuscates the class names. I guess it does not change the names of the classes stored in the index files produced by the ClassIndex. This needs to be fixed on the ProGuard side.
