### ISSUE TITLE
unable to get groovy classes annotated with @IndexAnnotated

### ISSUE THREAD

**Issue by yugantshah** [atteo/classindex#41]
ClassFilter.only().topLevel().from(ClassIndex.getAnnotated(<Annotation>.class)) does not get groovy classes

**Comment by sentinelt** [comment]
As I am not a Groovy user it is hard for me to reproduce the problem. Would you be so kind to provide me with a sample Groovy project which shows the problem?

Then I will be able to pinpoint the cause of the issue.

**Comment by sentinelt** [comment]
Closing for now, if it is still an issue please provide a minimal example to reproduce it.
