### ISSUE TITLE
Java 9, modulepath and jrt URLs

### ISSUE THREAD

**Issue by kaqqao** [atteo/classindex#42]
There's a talk about Java 9 support in all similar libraries. E.g. [here's](https://github.com/ronmamo/reflections/issues/186#issuecomment-320408935) the relevant issue in Reflections, and this library was mentioned.

What's the status on Java 9 support here?

**Comment by sentinelt** [comment]
Hi, I haven't tested the Classindex with Java 9 yet. I will probably give it a try next week. I expect less compatibility issues with changes made in classloaders mechanics as Classindex is not based on runtime reflections and instead does compile time indexing.

I will add some unit tests to ensure the correctness. In the meantime let me know if you find and issues with it.

**Comment by kaqqao** [comment]
It's not the classesloader changes that worry me, but the fact that classpath as such is now kind of a legacy thing. Now each module has its own modulepath, and those can now contain not only file system paths to JAR or class files, but the newly specified `jrt://` URLs. Without explicit support for these, I think the scanning would work only in a limited set of cases.
This is currently the situation is most libraries...

There's some helpful hints in my [SO thread](https://stackoverflow.com/questions/41932635/scanning-classpath-modulepath-in-runtime-in-java-9/45612376#45612376).

**Comment by kaqqao** [comment]
Btw, pardon my ignorance here, how does ClassIndex decide what paths to scan? Since it all happens at compile time, there's no such thing as classpath yet to tell it.

**Comment by sentinelt** [comment]
Classindex analyses the classes as they are compiled. And so must be present on the classpath during compilation. For each compilation unit several indexes are created for all the classes which where compiled. Those indexes are then stored as a resources so they can be retrieved from the classpath at run-time. For instance, if you have a Maven project which builds a jar file then the indexes will take into account all the classes from this jar file, but not from any dependencies of this project. This means you will not get the classes from 3rd party libraries by default.

At runtime, when (for instance) you query for the classes implementing given interface, all the indexes which are reachable from the current context are analysed.

Using URLClassLoader, depending on its logic and assuming it's the only type of ClassLoader used was always a kind of hack IMHO. Instead Classindex uses [annotation processing](https://docs.oracle.com/javase/9/docs/api/javax/annotation/processing/package-summary.html) and reflection API. Although annotation processing is rough around the edges, especially when doing incremental compilation, it works pretty well with some workarounds applied.

**Comment by kaqqao** [comment]
Ah, I understand now. Thanks for the explanation!

Since it doesn't scan 3rd party classes (including JDK's own), it doesn't sound like it should be bothered much by the Java 9 changes.

**Comment by sentinelt** [comment]
I run it currently on Java 9. Looks OK. Although we do not use much of the new Jigsaw stuff.

**Comment by lukehutch** [comment]
Hi, I figured out how to scan modules, in case you are interested in adding support for this.

https://stackoverflow.com/a/45612376/3950982

**Comment by bmarwell** [comment]
hey everyone. This is closed, BUT I have some information for you.
In Module 1, I am using the APT to generate the info files. In this module, just use `require static org.atteo.classindex` on your `module-info.java`.
In Module 2, I only use it for tests – no additional requirements needed.

HTH
