### ISSUE TITLE
No index file is generated after compile

### ISSUE THREAD

**Issue by saadhamouine** [atteo/classindex#44]
I have added classindex 3.4 as a maven dependency. The jar is included in the project classpath.

I'm using the @IndexSubclasses annotation on a class but after i compile no index file is generated.
Does this work or am I missing a step?

I would appreciate some help!

**Comment by marembo2008** [comment]
The issue might be that the annotation processor was not marked up during the compile phase.
Which maven version are you using? This should normally be detected automatically through classpath scanning. You may need to add it explicitly on the maven-compiler-plugin, to determine that the plugin is actually failing to detect annotation processors in classpath:
https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#annotationProcessors

**Comment by saadhamouine** [comment]
I have added this in the maven compiler plugin config:
<annotationProcessorPaths>
	<path>
		<groupId>org.atteo.classindex</groupId>
	        <artifactId>classindex</artifactId>
		<version>3.4</version>
	 </path>
</annotationProcessorPaths>

but still nothing.

**Comment by sentinelt** [comment]
@saadhamouine Hi, I'm just guessing, but maybe you are missing the fact, that @IndexSubclasses marks a class (or interface) whose subclasses (classes implementing interface) should be indexed?

**Comment by sentinelt** [comment]
@saadhamouine 

I have also created a simple example: https://github.com/atteo/classindex-maven-example.
After you 'mvn compile' the project, just see the content of file ' target/classes/META-INF/services/org.example.Entity'

**Comment by saadhamouine** [comment]
@sentinelt  Hi, thank you for your response. what do you mean by subclasses should be indexed?

**Comment by saadhamouine** [comment]
@sentinelt  I have used your sample maven project and the file was generated yith this content: 
org.example.MyEntity

So what am i missing in my project?

**Comment by saadhamouine** [comment]
@sentinelt it's still not totaly working because jaxb doesn't fine the index files for data binding.

**Comment by pospears** [comment]
I have been unable to generate an index file as well, using Java 17 and mvn version 3.9.7
