### ISSUE TITLE
Removing dependency to jaxb-api

### ISSUE THREAD

**Issue by Yannic92** [atteo/classindex#49]
As far as I see the only reason for the jaxb-api dependency is that it is used in a JavaDoc comment.
Wouldn't it be better to exclude this from dependencies?
It doesn't seem to be worth adding a dependency just to mention it in a JavaDoc comment.

It might be possible that I just didn't see where you're actually using this dependency.

**Comment by sentinelt** [comment]
Fixed. I will release new version shortly. Thanks.
