### ISSUE TITLE
Not working with Eclipse?

### ISSUE THREAD

**Issue by nkavian** [atteo/classindex#5]
I created a new Java project in Eclipse, added the evo and guava jars, followed the example in the "Usage", but I don't see any index file being generated and it doesn't print out what it's supposed to print out.

What am I missing?

Using evo-classindex-1.3.jar and guava-14.0.1.jar

It only print out the first line, not the others:

```
  System.out.println("!!!! Hello");
  for(final Class<?> klass : ClassIndex.getAnnotated(Entity.class))
     {
     System.out.println("!!!! " + klass.getName());
     }
```

Eclipse Juno on a Mac

**Comment by costaplih** [comment]
hi sentinelt,
I have an issue with your framework, i use 3.3 version, all is working fine from eclipse but when exporting to runnnable jar its not working any more (the jar is runnuble and working only the mechanism is not)
