### ISSUE TITLE
Project URL in POM results in HTTP 404

### ISSUE THREAD

**Issue by ST-DDT** [atteo/classindex#55]
The URL in your pom

http://atteo.org/static/classindex/classindex

is not accessible by normal browsers, please change it to point to a valid page (or at least configure a redirect).

Ref: https://github.com/atteo/classindex/blob/master/pom.xml#L16 (+ sub-projects)

PS: Please also change that URL to `https`

**Comment by sentinelt** [comment]
Redirected.
