### ISSUE TITLE
ClassIndex.getAnnotated(MyAnnotation.class) returns no results

### ISSUE THREAD

**Issue by TheDutchMC** [atteo/classindex#66]
Hi,

``ClassIndex.getAnnotated(PluginCommandExecutor.class)`` returns no results for me:
```java
@Documented
@IndexAnnotated
public @interface PluginCommandExecutor {}
```
I've double checked that the final jar contains ``META-INF/annotations/*``, and that it contains ``nl.thedutchmc.multiplayerevents.annotations.PluginCommandExecutor``, which it does.

Though when calling the in the title mentioned method no results are returned. If it matters any, this is a Minecraft Spigot plugin, which uses it's own classloader.

**Comment by sentinelt** [comment]
@TheDutchMC try specifying classloader, by using `ClassIndex.getAnnotated(Class<? extends Annotation> annotation, ClassLoader classLoader)`. By default context classloader of the current thread is used.

**Comment by TheDutchMC** [comment]
Yep that seems to do it, thanks!
