### ISSUE TITLE
Returns classes that are no longer annotated.

### ISSUE THREAD

**Issue by legaciespanda** [atteo/classindex#75]
I created a custom java annotation to be used on my classes. I used classindex to retrieve all the classes using my custom annotation. which works pretty fine.

The problem is, when i remove the custom annotation from those classes, **classindex** library still retrieves the list of classes i removed the annotations from. Returns classes that are no longer annotated.

I think it's some sort of a cache from **classindex**. Can it be disabled?

**Comment by sentinelt** [comment]
Duplicate of #54
